- name: "Setup Conda AMI for Deep Learning on govuk-taxonomy-supervised-learning"
  hosts: all
  become: true

  tasks:

    - name: format the EBS filesystem
      filesystem:
        fstype: ext4
        dev: /dev/xvdh

    - name: configure the EBS volume mount point
      mount:
        path: /data
        src: /dev/xvdh
        fstype: ext4
        state: present

    - name: mount the EBS volume
      mount:
        path: /data
        src: /dev/xvdh
        fstype: ext4
        state: mounted

    - name: Clone latest govuk-taxonomy-supervised-learning 
      git:
        repo: https://github.com/alphagov/govuk-taxonomy-supervised-learning.git
        dest: /home/ubuntu/govuk-taxonomy-supervised-learning
      become_user: ubuntu

    - name: Install scikit-learn 0.19.1
      pip:
        name: scikit-learn
        version: 0.19.1
        virtualenv: /home/ubuntu/anaconda3/envs/tensorflow_p36

    - name: Install lxml 4.1.1
      pip:
        name: lxml
        version: 4.1.1
        virtualenv: /home/ubuntu/anaconda3/envs/tensorflow_p36
